<?php
define('QQ_AKEY','');
define('QQ_SKEY','');
define('QQ_BACK','');
define('WB_AKEY','');
define('WB_SKEY','');
define('WB_BACK','');
define('BD_AKEY','');
define('BD_SKEY','');
define('BD_BACK','');
define('GG_AKEY','');
define('GG_SKEY','');
define('GG_BACK','');
define('WL_AKEY','');
define('WL_SKEY','');
define('WL_BACK','');
define('DB_AKEY','');
define('DB_SKEY','');
define('DB_BACK','');
define('RR_AKEY','');
define('RR_SKEY','');
define('RR_BACK','');
define('KX_AKEY','');
define('KX_SKEY','');
define('KX_BACK','');
?>
